import type { Metadata } from "next";
import { Inter, Sacramento, Source_Code_Pro } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import AdSense from "./component/AdSenseScript";

const inter = Inter({ subsets: ["latin"] });
const scp = Source_Code_Pro({ subsets: ["latin"] });
const sacramento = Sacramento({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "BingBlong AI",
  description: "Generated by swing media",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <AdSense pId="ca-pub-4592814778191453"/>
        <Script 
          src="//produceragony.com/1d/8c/09/1d8c0950213135ab99eaa34cc2de75a9.js"
          strategy="afterInteractive"
        />
      </head>
      <body className={scp.className}>
        {children}
        <Script 
          async 
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4592814778191453"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
        <ins className="adsbygoogle"
             style={{ display: "block" }}
             data-ad-client="ca-pub-4592814778191453"
             data-ad-slot="1158100898"
             data-ad-format="auto"
             data-full-width-responsive="true"></ins>
        <Script id="adsbygoogle-init" strategy="afterInteractive">
          {`(adsbygoogle = window.adsbygoogle || []).push({});`}
        </Script>
      </body>
    </html>
  );
}
